name: CI
on : [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build application
        run: make test
      - name: upload the build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            test
          retention-days: 1
  run-test:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - name: download the build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
      - name: run tests
        run: chmod +x ./test && ./test